# Generated by Django 4.0.5 on 2022-06-27 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('email', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=10)),
                ('age', models.CharField(max_length=10)),
                ('biography', models.TextField()),
                ('job_role', models.CharField(max_length=30)),
                ('interest', models.CharField(max_length=30)),
                ('active', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Verify',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=10)),
                ('email', models.CharField(max_length=50)),
                ('time', models.DateTimeField()),
            ],
        ),
    ]
